# Generated by Django 3.2.5 on 2021-08-13 04:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_host_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='games_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='games_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='games_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_against',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='goals_for',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='saves',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='shutouts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='strikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='team_leader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='tourneys_lost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tourneys_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='tourneys_won',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourney',
            name='age_group',
            field=models.CharField(choices=[('youth', 'Youth'), ('preteen', 'Pre-teen'), ('teen', 'Teen'), ('youngadult', 'Young Adult'), ('adult', 'Adult'), ('mixed', 'Mixed')], default='Mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='tourney',
            name='current_participants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user'),
        ),
        migrations.AddField(
            model_name='tourney',
            name='duration_points',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(3), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='tourney',
            name='gender',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens')], default='Mens', max_length=20),
        ),
        migrations.AddField(
            model_name='tourney',
            name='max_participants',
            field=models.PositiveIntegerField(default=32, validators=[django.core.validators.MinValueValidator(6), django.core.validators.MaxValueValidator(64)]),
        ),
        migrations.AddField(
            model_name='tourney',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='team_size',
            field=models.CharField(blank=True, choices=[('3v3', '3v3'), ('4v4', '4v4'), ('5v5', '5v5'), ('6v6', '6v6'), ('7v7', '7v7'), ('8v8', '8v8'), ('9v9', '9v9'), ('10v10', '10v10'), ('11v11', '11v11')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('mens', 'Mens'), ('womens', 'Womens')], default='Mens', max_length=20),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=100)),
                ('direction', models.CharField(choices=[('buy', 'Buy'), ('earn', 'Earn')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tourney')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('home_points', models.PositiveIntegerField(default=0)),
                ('away_points', models.PositiveIntegerField(default=0)),
                ('home_scorers', models.CharField(blank=True, max_length=50, null=True)),
                ('away_scorers', models.CharField(blank=True, max_length=50, null=True)),
                ('teams', models.ManyToManyField(blank=True, null=True, to='api.Team')),
                ('venue', models.ManyToManyField(blank=True, null=True, to='api.Tourney')),
            ],
        ),
    ]
