# Generated by Django 3.2.5 on 2021-08-13 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210813_0457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='venue',
        ),
        migrations.AddField(
            model_name='game',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.tourney'),
        ),
    ]
