# Generated by Django 3.2.6 on 2021-08-13 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_game_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='city',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='lat_coord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourney',
            name='lon_coord',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, null=True, to='api.Team'),
        ),
    ]
