# Generated by Django 3.2.6 on 2021-08-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_host_host_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Mens', 'Mens'), ('Womens', 'Womens')], default='Mens', max_length=20),
        ),
    ]
