# Generated by Django 3.2.6 on 2021-08-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='membership',
            field=models.CharField(choices=[('free', 'Free'), ('certified', 'Certified')], default='free', max_length=50),
        ),
    ]
