# Generated by Django 3.2.5 on 2021-08-13 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20210813_0436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='current_participants',
        ),
        migrations.AddField(
            model_name='tourney',
            name='current_participants',
            field=models.ManyToManyField(blank=True, null=True, to='api.User'),
        ),
    ]
