# Generated by Django 3.2.5 on 2021-08-13 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210813_0447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='strikes',
            new_name='shots',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='strikes',
            new_name='shots',
        ),
    ]
