# Generated by Django 3.2.5 on 2021-08-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210813_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, max_length=2, null=True, to='api.Team'),
        ),
    ]
