# Generated by Django 3.2.6 on 2021-08-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210813_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='away_scorers',
            new_name='loser',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='away_points',
            new_name='loser_points',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_scorers',
            new_name='loser_scorers',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='home_points',
            new_name='winner_points',
        ),
        migrations.AddField(
            model_name='game',
            name='winner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='winner_scorers',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
