self.addEventListener('install', (e) => {
    e.waitUntil(
      caches.open('fox-store').then((cache) => cache.addAll([
        '/',
        '/views/add_tourney.ejs',
        '/views/balance.ejs',
        '/views/create_team.ejs',
        '/views/friends.ejs',
        '/views/home.ejs',
        '/views/host_home.ejs',
        '/views/host_signup.ejs',
        '/views/host_tourney_details.ejs',
        '/views/join_team.ejs',
        '/views/leaderboard.ejs',
        '/views/login.ejs',
        '/views/manage_tourney.ejs',
        '/views/match_score.ejs',
        '/views/no_team.ejs',
        '/views/preorder.ejs',
        '/views/profile_player.ejs',
        '/views/register.ejs',
        '/views/signedup.ejs',
        '/views/summary.ejs',
        '/views/team_player.ejs',
        '/views/tourney_details.ejs',
        '/views/tourney_end.ejs',
        '/views/unverified.ejs',
        '/views/verify_login.ejs',
        '/views/winner.ejs',
        '/images/',
        '/images/Arrow Icon.png',
        '/images/back.png',
        '/images/back_inverted.png',
        '/images/favicon.png',
        '/images/Filter Icon.png',
        '/images/Fireworks.png',
        '/images/Flame.png',
        '/images/home.png',
        '/images/icon.png',
        '/images/MoneyTrophy.png',
        '/images/MyTourney Logo Soccer Inverted.png',
        '/images/MyTourney Logo.png',
        '/images/MyTourney Trophy Logo.png',
        '/images/rank1.png',
        '/images/rank2.png',
        '/images/rank3.png',
        '/images/Search Icon.png',
        '/images/share.png',
        '/images/share2.png',
        '/images/share_inverted.png',
        '/images/Soccer.png',
        '/images/Sort Icon.png',
        '/images/summary.png',
        '/images/tourneyTrophy.png',
        '/images/trashcan.png',
        '/images/Up Arrow.png',
        '/images/default_profile.jpg',
        '/images/favicon.ico',
        '/images/Up Arrow.jpeg',
        '/css/addtohomescreen.css',
        '/css/styles.css',
        '/css/NTF-Grand-Regular.woff',
        '/css/VarsityRegular.woff',
        '/css/NTF-Grand-Regular.woff2',
        '/css/VarsityRegular.woff2',
        '/css/addtohomescreen.js',
        '/css/addtohomescreen.min.js',
        '/css/annihilator.js',
        '/css/app.js',
        '/css/email.js',
        '/css/forgot.js',
        '/css/location.js',
        '/css/login.js',
        '/css/match.js',
        '/css/matchlink.js',
        '/css/passport-config.js',
        '/css/spaces.js',
        '/css/sw.js',
        '/css/webapp.js'
      ])),
    );
  });
  
  self.addEventListener('fetch', (e) => {
    console.log(e.request.url);
    e.respondWith(
      caches.match(e.request).then((response) => response || fetch(e.request)),
    );
  });